name: LFSLockManger-Updater

on:
  push:
    branches:
      - main

jobs:
  download-release:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Get latest release info
        id: get-release
        run: |
          owner="chillpert"
          repo="lfs-lock-manager"
          release=$(curl -s "https://api.github.com/repos/$owner/$repo/releases/latest" | grep -oP '"tag_name": "\K(.*)(?=")')
          echo "::set-output name=release::$release"

      - name: Get LFSLockManager version
        run: echo "MYVAR=${{ vars.MYVAR }}" >> $GITHUB_ENV

      - name: Set Environment Variables
        uses: tw3lveparsecs/github-actions-set-variables@latest
        with:
          envFilePath: ./.github/variables/vars.env

      - name: Compare MyVar with tag name
        id: compare
        env:
          GH_TOKEN: ${{ github.token }}
        run: |
          echo "HERE: $LFSLOCKMANAGER == ${{ steps.get-release.outputs.release }}"
          if [[ "$LFSLOCKMANAGER" == "${{ steps.get-release.outputs.release }}" ]]; then
            echo "::set-output name=isMatched::true"
            echo "Version is same"
            echo "::set-output name=my_variable::true"
            gh run cancel ${{ github.run_id }}
          else
            echo "::set-output name=isMatched::false"
            echo "Version is different"
            # echo "LFSLOCKMANAGER=${{ steps.get-release.outputs.release }}" >> ./.github/variables/vars.env
            sed -i "s/\(LFSLOCKMANAGER=\).*/\1${{ steps.get-release.outputs.release }}/" ./.github/variables/vars.env
          fi

      - name: Download release
        if: steps.set_variable.outputs.my_variable != 'true'
        run: |
          owner="chillpert"
          repo="lfs-lock-manager"
          release="${{ steps.get-release.outputs.release }}"
          asset_url="https://github.com/$owner/$repo/releases/download/$release/LfsLockManager_Windows.zip"
          curl -L -o asset.zip "$asset_url"
          unzip asset.zip

      - name: Configure Git
        if: steps.set_variable.outputs.my_variable != 'true'
        run: |
          git config user.name 'github-actions[bot]'
          git config user.email 'github-actions[bot]@users.noreply.github.com'

      - name: Commit changes
        if: steps.set_variable.outputs.my_variable != 'true'
        run: |
          ls -a
          git add LfsLockManager.exe
          git add ./.github/variables/vars.env
          git commit -m "Update LFS lock manager to latest"
          git push
